[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
clap = { version = "4.5.32", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
reqwest = { version = "0.12.14", features = ["json"] }
anyhow = "1.0.97"
